# Generated by Django 5.0.4 on 2024-04-26 13:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='centre',
            field=models.CharField(default='I.E.S. Esteve Terradas i Illa', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='tipus',
            field=models.CharField(choices=[('usuari', 'Usuari'), ('admin', 'Admin'), ('super-usuari', 'Super Usuari')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
